### ISSUE TITLE
Paths not updating if file not present at `outDir`

### ISSUE THREAD

**Issue by tcK1** [justkey007/tsc-alias#116]
Hey! First of all, thanks for the package.

I don't know if this is intended behavior or not, so sorry if I'm missing something here. When calling the replace algorithm programmatically for a single file (or more specifically, a string), if the file it's currently working on does not exist it won't update the paths. If I ran the exact same thing 2 times, the second one (when the file is on disk) will work as intended.

I don't know if I explained it well enough, so I made a repo with this behavior: https://github.com/tcK1/tsc-alias-behavior-repro

**How to reproduce:**

First, run `yarn install` to add the dependencies.

Then run `yarn build` for the first time, this will produce files on the `dist/` folder, check the `index.js` file and we will see that it was not updated. Run `yarn build` again and now it will work.

The build script can be found under `scripts/build.js`.

**Alternatives:**

Using `replaceTscAliasPaths` works correctly. I assume because the files are already on disk when we call the function.

**Comment by raouldeheer** [comment]
@tcK1 Tsc-alias looks for the file that is being imported, when that isn't present Tsc-alias continues with another path. When no file is found that resolves the alias, the alias isn't replaced. Because tsc-alias assumes the import is not on disk at the locations so it must be something else like node_modules or builtin etc.

**Comment by tcK1** [comment]
Got it! Thanks for the answer!
